const STORAGE_KEY='studentAcademicAnalyzer.v2';
const SETTINGS_KEY='studentAcademicAnalyzer.settings.v1';
const THEME_KEY='studentAcademicAnalyzer.theme.v1';
const BATCHES_KEY='studentAcademicAnalyzer.batches.v1';
const DEPARTMENTS_KEY='studentAcademicAnalyzer.departments.v1';
const DEFAULT_SETTINGS={internal:60,assignment:10,unitTest:15,exam:100};
const DEFAULT_BATCHES=['2025-29'];
const DEFAULT_DEPARTMENTS=['Artificial Intelligence and Data Science','Biomedical Engineering','Chemical Engineering','Civil Engineering','Computer Science and Business Systems','Computer Science and Engineering','Computer Science Engineering (AI & ML)','CSE (Cyber Security)','Electrical & Electronics Engineering','Electronics & Communication Engineering','Electronics Engineering (VLSI Design and Technology)','Information Technology','Mechanical Engineering','Mechatronics Engineering'];
function getDepartments(){try{const d=JSON.parse(localStorage.getItem(DEPARTMENTS_KEY)||'null');return Array.isArray(d)&&d.length?d:DEFAULT_DEPARTMENTS.slice()}catch{return DEFAULT_DEPARTMENTS.slice()}}
let DEPARTMENTS=getDepartments();
function saveDepartments(departments){DEPARTMENTS=[...new Set(departments.filter(Boolean).map(String))];localStorage.setItem(DEPARTMENTS_KEY,JSON.stringify(DEPARTMENTS));initDepartments();updateDepartmentUI();updatePrintFilters();renderTable()}
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const SUBJECTS_BY_DEPT={
'Artificial Intelligence and Data Science':['Python Programming','Data Science Fundamentals','Machine Learning','Statistics for Data Science','Database Systems','Artificial Intelligence'],
'Biomedical Engineering':['Biomedical Instrumentation','Human Anatomy','Biochemistry','Medical Imaging','Biomaterials','Signals and Systems'],
'Chemical Engineering':['Chemical Process Calculations','Fluid Mechanics','Heat Transfer','Mass Transfer','Chemical Reaction Engineering','Process Control'],
'Civil Engineering':['Engineering Mechanics','Structural Analysis','Fluid Mechanics','Geotechnical Engineering','Concrete Technology','Surveying'],
'Computer Science and Business Systems':['Data Structures','Object Oriented Programming','Database Management Systems','Operating Systems','Computer Networks','Business Analytics'],
'Computer Science and Engineering':['Data Structures','Object Oriented Programming','Database Management Systems','Operating Systems','Computer Networks','Software Engineering'],
'Computer Science Engineering (AI & ML)':['Digital Principles and Computer Organization','Object Oriented Programming Using Java','Data Structures','Object Oriented Programming Using Java Laboratory','Database Management Systems','Database Management Systems Laboratory','Software Engineering','Probability and Statistical Modeling for Computing Systems','Professional Skill Development - I','Essence of Indian Traditional Knowledge','AWS Fundamentals','Innovation Through Engineering Thinking'],
'CSE (Cyber Security)':['Network Security','Cyber Security Fundamentals','Cryptography','Ethical Hacking','Digital Forensics','Secure Software Engineering'],
'Electrical & Electronics Engineering':['Circuit Theory','Electrical Machines','Power Systems','Control Systems','Power Electronics','Electrical Measurements'],
'Electronics & Communication Engineering':['Digital Electronics','Analog Circuits','Signals and Systems','Communication Systems','Microprocessors','Electromagnetic Theory'],
'Electronics Engineering (VLSI Design and Technology)':['Digital System Design','VLSI Design','Analog IC Design','Semiconductor Devices','Embedded Systems','Computer Architecture'],
'Information Technology':['Web Technology','Cloud Computing','Software Engineering','Data Mining','Cyber Security','Mobile Application Development'],
'Mechanical Engineering':['Engineering Mechanics','Thermodynamics','Fluid Mechanics','Manufacturing Technology','Machine Design','CAD/CAM'],
'Mechatronics Engineering':['Sensors and Transducers','Robotics','Control Engineering','Embedded Systems','Manufacturing Automation','Mechatronics Design']
};
const DEPT_CODES={'Artificial Intelligence and Data Science':'AIDS','Biomedical Engineering':'BME','Chemical Engineering':'CHE','Civil Engineering':'CIV','Computer Science and Business Systems':'CSBS','Computer Science and Engineering':'CSE','Computer Science Engineering (AI & ML)':'AIML','CSE (Cyber Security)':'CYB','Electrical & Electronics Engineering':'EEE','Electronics & Communication Engineering':'ECE','Electronics Engineering (VLSI Design and Technology)':'VVT','Information Technology':'IT','Mechanical Engineering':'MECH','Mechatronics Engineering':'MTRX'};
const DEMO_NAMES=['Aarav','Aadhya','Abhinav','Adithya','Akash','Akshaya','Amal','Amrutha','Ananya','Arjun','Arun','Ashwin','Bala','Bharath','Bhavya','Chandru','Charan','Deepak','Dhanush','Divya','Dinesh','Gautham','Gayathri','Harish','Haritha','Hari','Ishaan','Ishita','Jeeva','Karthik','Kavya','Keerthana','Kiran','Krishna','Lokesh','Madhavan','Manoj','Meena','Mohamed','Nandhini','Naveen','Nikhil','Pavithra','Pranav','Priya','Rahul','Rakesh','Ravi','Reshma','Rohit','Sanjay','Sanjana','Saranya','Sathish','Shalini','Shivani','Siddharth','Sneha','Sowmya','Surya','Swetha','Tarun','Tejas','Vignesh','Vikram','Vinoth','Vishal','Yamini','Yash','Yogesh','Zoya'];
const DEMO_SURNAME=['Kumar','Sharma','Das','Krishnan','Singh','Patel','Reddy','Nair','Menon','Iyer','Rao','Joseph','Thomas','Mishra','Gupta','Verma','Khan','Ali','Bose','Choudhary'];
function demoRand(seed){const x=Math.sin(seed*12.9898)*43758.5453;return x-Math.floor(x)}
function makeDemoStudent(dept,i){const code=DEPT_CODES[dept],section=['A','B','C'][Math.floor(i/70)%3],name=`${DEMO_NAMES[i%DEMO_NAMES.length]} ${DEMO_SURNAME[Math.floor(i/DEMO_NAMES.length)%DEMO_SURNAME.length]}`;const base=48+demoRand(i*17+code.length)*42;const attendance=Math.max(58,Math.min(98,Math.round(72+demoRand(i*29+3)*26)));const previous=Math.max(52,Math.min(96,Math.round(base-4+demoRand(i*31+7)*12)));const subjectNames=SUBJECTS_BY_DEPT[dept];const subjects=subjectNames.map((sub,j)=>{const variance=(demoRand(i*43+j*11+5)-.5)*18;const pct=Math.max(42,Math.min(96,base+variance));return [sub,+(DEFAULT_SETTINGS.internal*(pct/100)).toFixed(1),+(DEFAULT_SETTINGS.assignment*(Math.min(100,pct+demoRand(i+j+8)*8)/100)).toFixed(1),+(DEFAULT_SETTINGS.unitTest*(Math.min(100,pct+demoRand(i+j+12)*8)/100)).toFixed(1),+(DEFAULT_SETTINGS.exam*(Math.min(100,pct+demoRand(i+j+19)*10)/100)).toFixed(1)]});return{id:`${code}${String(i+1).padStart(3,'0')}`,name,department:dept,section,batch:'2025-29',semester:String(1+(i%8)),attendance,previous,subjects}}
const DEMO=DEPARTMENTS.flatMap((dept)=>Array.from({length:210},(_,i)=>makeDemoStudent(dept,i)));

function getSettings(){try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return {...DEFAULT_SETTINGS}}}
let settings=getSettings();
function load(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');let changed=false;const normalized=data.map(s=>{if(!s.batch){changed=true;return {...s,batch:'2025-29'}}if('year' in s){changed=true;const n={...s};delete n.year;return n}return s});if(changed)localStorage.setItem(STORAGE_KEY,JSON.stringify(normalized));return normalized}catch{return[]}}
function getBatches(){try{const b=JSON.parse(localStorage.getItem(BATCHES_KEY)||'null');return Array.isArray(b)&&b.length?b:DEFAULT_BATCHES.slice()}catch{return DEFAULT_BATCHES.slice()}}
function saveBatches(batches){localStorage.setItem(BATCHES_KEY,JSON.stringify([...new Set(batches.filter(Boolean).map(String))]));updateBatchUI()}
function save(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));updateSectionFilter();updateAnalyticsSemesterFilter();renderTable();updatePrintFilters();populatePrintStudentOptions()}
function getTheme(){return localStorage.getItem(THEME_KEY)||'white-multi'}
function setTheme(theme){const allowed=['white-blue','white-red','white-black','white-green','white-purple','black-white','black-green','black-red','black-blue'];const t=allowed.includes(theme)?theme:'white-blue';document.body.dataset.theme=t;localStorage.setItem(THEME_KEY,t);if($('themeSetting'))$('themeSetting').value=t}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));updateSettingsUI();refreshSubjectRows();let s=currentStudent();if(s)analyze(s);renderTable()}
function currentStudent(){let id=$('studentId').value.trim();return load().find(s=>s.id===id)||null}
function subjectScore(x){const vals=[+x[1]||0,+x[2]||0,+x[3]||0,+x[4]||0];const pct=[vals[0]/settings.internal,vals[1]/settings.assignment,vals[2]/settings.unitTest,vals[3]/settings.exam].map(v=>Math.max(0,Math.min(1,v)));return +((pct.reduce((a,b)=>a+b,0)/4)*100).toFixed(1)}
function averageSubject(s){const a=(s.subjects||[]).map(subjectScore);return a.length?+(a.reduce((x,y)=>x+y,0)/a.length).toFixed(1):0}
function score(s){return +(averageSubject(s)*0.85+s.attendance*0.15).toFixed(1)}
function gradePoint(p){if(p>=90)return 10;if(p>=80)return 9;if(p>=70)return 8;if(p>=60)return 7;if(p>=50)return 6;if(p>=40)return 5;return 0}
function cgpa(s){const a=(s.subjects||[]).map(x=>gradePoint(subjectScore(x)));return a.length?+(a.reduce((x,y)=>x+y,0)/a.length).toFixed(2):0}
function resultBand(p){if(p>=90)return['O','Outstanding'];if(p>=80)return['A+','Excellent'];if(p>=70)return['A','Very Good'];if(p>=60)return['B+','Good'];if(p>=50)return['B','Pass'];if(p>=40)return['C','Needs Improvement'];return['F','Fail']}
function performanceStatus(p){return p<50?'Arrear / Failed':p<70?'Less Performance':'Good Performance'}
function arrearSubjects(s){return (s.subjects||[]).map(x=>[x,subjectScore(x)]).filter(x=>x[1]<50)}
function arrearMessage(s){const n=arrearSubjects(s).length;return n?`Arrear in ${n} subject${n===1?'':'s'}`:''}
function attendanceStatus(a){return a<75?'Low':a<90?'Medium':'Good'}
function attendanceClass(a){const v=attendanceStatus(a);return v==='Low'?'bad':v==='Medium'?'warn':'good'}
function trend(s){if(!s.previous)return'New baseline';let d=score(s)-s.previous;return d>=5?'Improving':d<=-5?'Declining':'Stable'}
function recommendations(s){let a=[];if(s.attendance<75)a.push(`Increase attendance from ${s.attendance}% toward at least 75%.`);const weak=(s.subjects||[]).map(x=>[x,subjectScore(x)]).sort((a,b)=>a[1]-b[1]);weak.slice(0,2).filter(x=>x[1]<60).forEach(x=>a.push(`Prioritize ${x[0][0]} (${subjectScore(x)}%) with extra practice and doubt-clearing.`));if((s.subjects||[]).some(x=>+x[4]/settings.exam<.55))a.push('Focus on final-semester exam preparation and previous-question papers.');if((s.subjects||[]).some(x=>+x[1]/settings.internal<.6))a.push('Review internal-test topics with targeted teacher feedback.');if((s.subjects||[]).some(x=>+x[2]/settings.assignment<.7))a.push('Complete assignments consistently before deadlines.');if(!a.length)a.push('Maintain the current study routine and regular revision.');return a.slice(0,5)}
function focusNextMark(input){const marks=[...input.closest('.subject-card').querySelectorAll('.sub-internal,.sub-assignment,.sub-unit,.sub-exam')];const i=marks.indexOf(input);if(i<0||i===marks.length-1)return;input.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key==='ArrowRight'){e.preventDefault();marks[i+1].focus();marks[i+1].select?.()}})}
function addSubject(x=['','','','','']){const row=document.createElement('div');row.className='subject-card';row.innerHTML=`<div class="subject-title"><input class="sub-name" placeholder="Subject name" value="${esc(x[0])}" required><button type="button" aria-label="Remove subject">×</button></div><div class="subject-marks"><label>Internal / <span class="max-internal">${settings.internal}</span><input class="sub-internal" type="number" min="0" max="${settings.internal}" step="0.1" value="${x[1]??''}" required></label><label>Assignment / <span class="max-assignment">${settings.assignment}</span><input class="sub-assignment" type="number" min="0" max="${settings.assignment}" step="0.1" value="${x[2]??''}" required></label><label>Unit Test / <span class="max-unit">${settings.unitTest}</span><input class="sub-unit" type="number" min="0" max="${settings.unitTest}" step="0.1" value="${x[3]??''}" required></label><label>Final Exam / <span class="max-exam">${settings.exam}</span><input class="sub-exam" type="number" min="0" max="${settings.exam}" step="0.1" value="${x[4]??''}" required></label></div><div class="subject-result">Subject Performance: <b class="sub-result">${subjectScore(x)}%</b></div>`;row.querySelector('button').onclick=()=>row.remove();const markInputs=[...row.querySelectorAll('.sub-internal,.sub-assignment,.sub-unit,.sub-exam')];markInputs.forEach((input,index)=>{focusNextMark(input);input.addEventListener('input',()=>{let v=[row.querySelector('.sub-name').value,+row.querySelector('.sub-internal').value||0,+row.querySelector('.sub-assignment').value||0,+row.querySelector('.sub-unit').value||0,+row.querySelector('.sub-exam').value||0];row.querySelector('.sub-result').textContent=subjectScore(v)+'%';const max=+input.max||100,n=String(Math.floor(max)).length,digits=String(input.value).replace(/[^0-9]/g,'').length;clearTimeout(input._advanceTimer);if(index<markInputs.length-1&&input.value!==''){if(digits>=n&&+input.value<=max){input._advanceTimer=setTimeout(()=>{markInputs[index+1].focus();markInputs[index+1].select?.()},80)}else{input._advanceTimer=setTimeout(()=>{if(document.activeElement===input&&input.value!==''){markInputs[index+1].focus();markInputs[index+1].select?.()}},1200)}}})});row.querySelectorAll('input').forEach(i=>{if(!i.matches('.sub-internal,.sub-assignment,.sub-unit,.sub-exam'))i.addEventListener('input',()=>{let v=[row.querySelector('.sub-name').value,+row.querySelector('.sub-internal').value||0,+row.querySelector('.sub-assignment').value||0,+row.querySelector('.sub-unit').value||0,+row.querySelector('.sub-exam').value||0];row.querySelector('.sub-result').textContent=subjectScore(v)+'%'})});$('subjects').appendChild(row)}
function refreshSubjectRows(){document.querySelectorAll('.subject-card').forEach(row=>{[['.max-internal',settings.internal,'.sub-internal'],['.max-assignment',settings.assignment,'.sub-assignment'],['.max-unit',settings.unitTest,'.sub-unit'],['.max-exam',settings.exam,'.sub-exam']].forEach(([label,max,input])=>{row.querySelector(label).textContent=max;row.querySelector(input).max=max});const v=[row.querySelector('.sub-name').value,+row.querySelector('.sub-internal').value||0,+row.querySelector('.sub-assignment').value||0,+row.querySelector('.sub-unit').value||0,+row.querySelector('.sub-exam').value||0];row.querySelector('.sub-result').textContent=subjectScore(v)+'%'})}
function updateBatchUI(){const batches=getBatches();const ids=['batch','printBatch','batchFilter'];ids.forEach(id=>{const el=$(id);if(!el)return;const current=el.value;const prefix=id==='batchFilter'?'<option value="ALL">All batches</option>':'';el.innerHTML=prefix+batches.map(b=>`<option value="${esc(b)}">Batch ${esc(b)}</option>`).join('');if(batches.includes(current))el.value=current;else if(id==='batchFilter'||id==='printBatch')el.value='ALL';else el.value=batches[0]||'2025-29';});const list=$('batchList');if(list)list.innerHTML=batches.map(b=>`<span class="batch-chip">Batch ${esc(b)} <button type="button" data-batch="${esc(b)}" ${b==='2025-29'?'disabled':''}>×</button></span>`).join('')}
function updateSettingsUI(){$('settingInternal').value=settings.internal;$('settingAssignment').value=settings.assignment;$('settingUnitTest').value=settings.unitTest;$('settingExam').value=settings.exam;$('legendInternal').textContent=`Internal / ${settings.internal}`;$('legendAssignment').textContent=`Assignment / ${settings.assignment}`;$('legendUnit').textContent=`Unit Test / ${settings.unitTest}`;$('legendExam').textContent=`Final Exam / ${settings.exam}`;if($('themeSetting'))$('themeSetting').value=getTheme()}
function updateDepartmentUI(){const list=$('departmentList');if(list)list.innerHTML=DEPARTMENTS.map(d=>`<div class="batch-item"><span>${esc(d)}</span><button type="button" class="danger" data-dept="${esc(d)}">Remove</button></div>`).join('')}
function initDepartments(){let d=$('department');if(d)d.innerHTML=DEPARTMENTS.map(x=>`<option>${esc(x)}</option>`).join('');populateDeptFilters();updateDepartmentUI()}
function populateDeptFilters(){let f=$('deptFilter'),pf=$('printDepartment');const current=f.value||'ALL',pc=pf?.value||'ALL';const options='<option value="ALL">All departments</option>'+DEPARTMENTS.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');f.innerHTML=options;if([...f.options].some(o=>o.value===current))f.value=current;if(pf){pf.innerHTML='<option value="ALL">All departments</option>'+DEPARTMENTS.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');pf.value=[...pf.options].some(o=>o.value===pc)?pc:'ALL'}}
function sectionsFor(data,dept='ALL'){return [...new Set(data.filter(s=>dept==='ALL'||s.department===dept).map(s=>s.section).filter(Boolean))].sort()}
function updateSectionFilter(){const data=load(),dept=$('deptFilter').value,sel=$('sectionFilter').value||'ALL',secs=sectionsFor(data,dept);$('sectionFilter').innerHTML='<option value="ALL">All sections</option>'+secs.map(s=>`<option value="${esc(s)}">Section ${esc(s)}</option>`).join('');if(secs.includes(sel))$('sectionFilter').value=sel;else $('sectionFilter').value='ALL';updateAnalyticsSemesterFilter()}
function updateAnalyticsSemesterFilter(){const data=load(),dept=$('deptFilter').value,section=$('sectionFilter').value,batch=$('batchFilter').value,sel=$('semesterFilter').value||'ALL';const semesters=[...new Set(data.filter(s=>(dept==='ALL'||s.department===dept)&&(section==='ALL'||s.section===section)&&(batch==='ALL'||String(s.batch)===batch)).map(s=>String(s.semester||'')).filter(Boolean))].sort((a,b)=>(+a)-(+b));$('semesterFilter').innerHTML='<option value="ALL">All semesters</option>'+semesters.map(x=>`<option value="${esc(x)}">Semester ${esc(x)} (${+x%2===0?'Even':'Odd'})</option>`).join('');$('semesterFilter').value=semesters.includes(sel)?sel:'ALL'}
function updatePrintFilters(){const data=load(),dept=$('printDepartment').value||'ALL',requestedSec=$('printSection').value||'ALL',requestedBatch=$('printBatch').value||'ALL',requestedSem=$('printSemester').value||'ALL';const secs=sectionsFor(data,dept);$('printSection').innerHTML='<option value="ALL">All sections</option>'+secs.map(s=>`<option value="${esc(s)}">Section ${esc(s)}</option>`).join('');const sec=secs.includes(requestedSec)?requestedSec:'ALL';$('printSection').value=sec;const deptData=data.filter(s=>(dept==='ALL'||s.department===dept)&&(sec==='ALL'||s.section===sec));const batches=[...new Set(deptData.map(s=>String(s.batch||'')).filter(Boolean))].sort();$('printBatch').innerHTML='<option value="ALL">All batches</option>'+batches.map(b=>`<option value="${esc(b)}">Batch ${esc(b)}</option>`).join('');const batch=batches.includes(requestedBatch)?requestedBatch:'ALL';$('printBatch').value=batch;const batchData=deptData.filter(s=>batch==='ALL'||String(s.batch)===batch);const semesters=[...new Set(batchData.map(s=>String(s.semester||'')).filter(Boolean))].sort((a,b)=>(+a)-(+b));$('printSemester').innerHTML='<option value="ALL">All semesters</option>'+semesters.map(x=>`<option value="${esc(x)}">Semester ${esc(x)} (${+x%2===0?'Even':'Odd'})</option>`).join('');$('printSemester').value=semesters.includes(requestedSem)?requestedSem:'ALL'}
function formStudent(){return{id:$('studentId').value.trim(),name:$('studentName').value.trim(),department:$('department').value,section:$('section').value.trim(),batch:$('batch').value,semester:$('semester').value,attendance:+$('attendance').value,previous:+$('previous').value||null,subjects:[...document.querySelectorAll('.subject-card')].map(r=>[r.querySelector('.sub-name').value.trim(),+r.querySelector('.sub-internal').value,+r.querySelector('.sub-assignment').value,+r.querySelector('.sub-unit').value,+r.querySelector('.sub-exam').value]).filter(x=>x[0])}}
function fill(s){$('studentId').value=s.id;$('studentName').value=s.name;$('department').value=s.department;$('section').value=s.section||'';$('batch').value=s.batch||getBatches()[0];$('semester').value=s.semester||'1';$('attendance').value=s.attendance;$('previous').value=s.previous??'';$('subjects').innerHTML='';(s.subjects||[]).forEach(x=>addSubject(x));analyze(s)}
function analyze(s){$('emptyState').classList.add('hidden');$('analysis').classList.remove('hidden');let sc=score(s),t=trend(s),avg=averageSubject(s),cp=cgpa(s),band=resultBand(sc),ps=performanceStatus(sc),as=attendanceStatus(s.attendance),am=arrearMessage(s);$('overallScore').textContent=sc+'%';$('scoreRing').style.background=`conic-gradient(var(--primary) ${Math.min(sc,100)*3.6}deg,#e8edf5 0deg)`;$('resultName').textContent=s.name;$('resultMeta').textContent=`${s.id} • ${s.department} • Section ${s.section} • Batch ${s.batch||'—'} • Semester ${s.semester}`;$('mSubjects').textContent=s.subjects.length;$('mAttendance').textContent=s.attendance+'%';$('mPrevious').textContent=s.previous??'—';$('mAverage').textContent=avg+'%';$('resultCgpa').textContent=cp.toFixed(2);$('resultGrade').textContent=band[0];$('resultGradeText').textContent=band[1];$('performancePill').textContent=ps;$('performancePill').className='pill '+(ps==='Good Performance'?'good':'bad');$('performanceBadge').textContent=ps;$('performanceBadge').className='status-badge '+(ps==='Good Performance'?'good':'bad');$('arrearBadge').textContent=am||'No subject arrears';$('arrearBadge').className='status-badge '+(am?'bad':'good');$('attendanceBadge').textContent=`Attendance ${as} • ${s.attendance}%`;$('attendanceBadge').className='status-badge '+attendanceClass(s.attendance);$('barChart').innerHTML=(s.subjects||[]).map(x=>{const p=subjectScore(x);return `<div class="bar-line"><span title="${esc(x[0])}">${esc(x[0])}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.min(p,100)}%"></div></div><b>${p}%</b></div>`}).join('')||'<small>No subjects added.</small>';$('recommendations').innerHTML=recommendations(s).map(x=>`<li>${esc(x)}</li>`).join('')}
function renderTable(){let data=load(),filter=$('deptFilter').value,section=$('sectionFilter').value,batch=$('batchFilter').value,semester=$('semesterFilter')?.value||'ALL',query=($('studentSearch')?.value||'').trim().toLowerCase();const wantsArrear=/\b(arrear|arrears|fail|failed|failure)\b/.test(query),wantsLess=/less\s*performance/.test(query),wantsGood=/good\s*performance/.test(query);let view=data.filter(s=>{const ps=performanceStatus(score(s));const textMatch=!query||String(s.id).toLowerCase().includes(query)||String(s.name).toLowerCase().includes(query)||((wantsArrear&&((ps==='Arrear / Failed')||arrearSubjects(s).length>0))||(wantsLess&&ps==='Less Performance')||(wantsGood&&ps==='Good Performance'));return (filter==='ALL'||s.department===filter)&&(section==='ALL'||s.section===section)&&(batch==='ALL'||String(s.batch)===batch)&&(semester==='ALL'||String(s.semester)===semester)&&textMatch});$('studentCount').textContent=data.length;$('kStudents').textContent=view.length;$('kAverage').textContent=view.length?(view.reduce((a,s)=>a+score(s),0)/view.length).toFixed(1)+'%':'0%';$('kAttendance').textContent=view.length?(view.reduce((a,s)=>a+s.attendance,0)/view.length).toFixed(1)+'%':'0%';$('kGood').textContent=view.filter(s=>performanceStatus(score(s))==='Good Performance').length;$('studentTable').innerHTML=view.map((s,rowIndex)=>{let ps=performanceStatus(score(s)),as=attendanceStatus(s.attendance),t=trend(s),recordIndex=data.indexOf(s);return `<tr><td>${esc(s.id)}</td><td>${esc(s.name)}</td><td>${esc(s.department)}</td><td>${esc(s.section||'—')}</td><td>${esc(s.batch||'—')}</td><td>Semester ${esc(s.semester||'—')}</td><td><b>${score(s)}%</b></td><td><b>${cgpa(s).toFixed(2)}</b></td><td>${s.attendance}%</td><td class="status-text ${attendanceClass(s.attendance)}"><b>${as}</b></td><td class="status-text ${ps==='Less Performance'||ps==='Arrear / Failed'?'bad':'good'}"><b>${ps}</b>${arrearMessage(s)?`<br><small class="arrear-inline">${arrearMessage(s)}</small>`:''}</td><td>${t}</td><td><div class="action-group"><button class="table-action" onclick="selectStudentRecord(${recordIndex})">View</button><button class="table-action clear-student" onclick="clearStudentData(${recordIndex})">Clear data</button></div></td></tr>`}).join('')||'<tr><td colspan="14" style="text-align:center;color:#7a8495;padding:30px">No students found.</td></tr>'}
window.selectStudent=id=>{let s=load().find(x=>x.id===id);if(s){fill(s);window.scrollTo({top:0,behavior:'smooth'})}};window.selectStudentRecord=index=>{const s=load()[index];if(s){fill(s);window.scrollTo({top:0,behavior:'smooth'})}};
window.clearStudentData=index=>{const data=load(),s=data[index];if(!s)return;const label=`${s.name} (${s.id}) — Semester ${s.semester||'—'}`;if(confirm(`Clear ${label}? This cannot be undone.`)){data.splice(index,1);save(data);if($('studentId').value.trim()===s.id&&String($('semester').value)===String(s.semester))$('clearForm').click();}};
function openSettings(){$('settingsPanel').classList.add('open');$('settingsBackdrop').classList.remove('hidden');$('settingsPanel').setAttribute('aria-hidden','false');$('menuButton').setAttribute('aria-expanded','true')}
function closeSettings(){$('settingsPanel').classList.remove('open');$('settingsBackdrop').classList.add('hidden');$('settingsPanel').setAttribute('aria-hidden','true');$('menuButton').setAttribute('aria-expanded','false')}
function openPrintModal(){populateDeptFilters();updatePrintFilters();populatePrintStudentSemesters();populatePrintStudentOptions();$('printStudentSearch').value='';$('printStudentSemester').value='ALL';populatePrintStudentSemesters();populatePrintStudentOptions();$('printScope').value='all';$('printDepartmentFields').classList.add('hidden');$('printStudentField').classList.add('hidden');$('printModal').classList.remove('hidden');$('printModal').setAttribute('aria-hidden','false')}
function closePrintModal(){$('printModal').classList.add('hidden');$('printModal').setAttribute('aria-hidden','true')}
function populatePrintStudentSemesters(){const data=load(),sel=$('printStudentSemester');if(!sel)return;const current=sel.value||'ALL';const semesters=[...new Set(data.map(s=>String(s.semester||'')).filter(Boolean))].sort((a,b)=>(+a)-(+b));sel.innerHTML='<option value="ALL">All semesters</option>'+semesters.map(x=>`<option value="${esc(x)}">Semester ${esc(x)} (${+x%2===0?'Even':'Odd'})</option>`).join('');sel.value=semesters.includes(current)?current:'ALL'}
function studentIdentityKey(s){return [s.id,s.name,s.department,s.section||'',s.batch||''].map(v=>String(v).trim().toLowerCase()).join('\u0001')}
function populatePrintStudentOptions(){const data=load(),query=($('printStudentSearch')?.value||'').trim().toLowerCase(),semester=$('printStudentSemester')?.value||'ALL',select=$('printStudent'),current=select?.value||'';if(!select)return;let matches=[];if(semester==='ALL'){const groups=new Map();data.forEach((s,i)=>{if(query&&!(String(s.id).toLowerCase().includes(query)||String(s.name).toLowerCase().includes(query)))return;const key=studentIdentityKey(s);if(!groups.has(key))groups.set(key,{s,i,semesters:[]});groups.get(key).semesters.push(String(s.semester||'—'))});matches=[...groups.values()].sort((a,b)=>String(a.s.name).localeCompare(String(b.s.name)))}else{matches=data.map((s,i)=>({s,i,semesters:[String(s.semester||'—')]})).filter(({s})=>(String(s.semester)===semester)&&(!query||String(s.id).toLowerCase().includes(query)||String(s.name).toLowerCase().includes(query)));matches.sort((a,b)=>String(a.s.name).localeCompare(String(b.s.name)))}select.innerHTML=matches.map(({s,i,semesters})=>{const labelSem=semester==='ALL'?`Semesters ${semesters.sort((a,b)=>(+a)-(+b)).join(', ')}`:`Semester ${esc(s.semester||'—')}`;return `<option value="${i}">${esc(s.name)} — ${esc(s.id)} — ${esc(s.department)} / ${esc(s.section||'')} • ${labelSem}</option>`}).join('')||'<option value="">No matching students</option>';if([...select.options].some(o=>o.value===current))select.value=current} 
function printScopeData(){const scope=$('printScope').value,data=load();if(scope==='student'){const idx=Number($('printStudent').value);if(!Number.isInteger(idx)||idx<0||idx>=data.length)return [];const selected=data[idx],sem=$('printStudentSemester')?.value||'ALL';if(sem!=='ALL')return [selected];const key=studentIdentityKey(selected);return data.filter(s=>studentIdentityKey(s)===key).sort((a,b)=>(+a.semester)-(+b.semester))}if(scope==='department'){const d=$('printDepartment').value,sec=$('printSection').value,batch=$('printBatch').value,sem=$('printSemester').value;return data.filter(s=>(d==='ALL'||s.department===d)&&(sec==='ALL'||s.section===sec)&&(batch==='ALL'||String(s.batch)===batch)&&(sem==='ALL'||String(s.semester)===sem))}return data}
function printStudentCard(s,index){const sc=score(s),ps=performanceStatus(sc),band=resultBand(sc),as=attendanceStatus(s.attendance),am=arrearMessage(s),subjects=(s.subjects||[]).map(x=>`${esc(x[0])}: ${subjectScore(x)}%`).join(' • ');return `<article class="print-student ${am?'has-arrear arrear-subject':''} ${ps==='Less Performance'?'less-performance':ps==='Arrear / Failed'?'arrear-failed':''}"><div class="print-student-head"><div><h2>${esc(s.name)}</h2><p>${esc(s.id)} • ${esc(s.department)} • Section ${esc(s.section||'—')} • Batch ${esc(s.batch||'—')}, Semester ${esc(s.semester)}</p></div><div class="print-score"><b>${sc}%</b><span>${ps}</span></div></div><div class="print-kpis"><div><span>CGPA</span><b>${cgpa(s).toFixed(2)}</b></div><div><span>Result</span><b>${band[0]}</b><small>${band[1]}</small></div><div><span>Attendance</span><b>${s.attendance}%</b><small class="att-${attendanceClass(s.attendance)}">${as}</small></div><div><span>Subject Avg.</span><b>${averageSubject(s)}%</b></div></div><div class="print-subjects"><b>Subjects:</b> ${subjects||'No subjects entered.'}</div>${am?`<div class="print-arrear-message">${esc(am)}</div>`:''}</article>`}
function departmentHeading(name){const map={'Computer Science and Engineering':'CSE','Computer Science Engineering (AI & ML)':'CSE (AI & ML)','Computer Science and Business Systems':'CSBS','Information Technology':'IT','Artificial Intelligence and Data Science':'AIDS','Biomedical Engineering':'BME','Chemical Engineering':'CHEM','Civil Engineering':'CIVIL','Electrical & Electronics Engineering':'EEE','Electronics & Communication Engineering':'ECE','Electronics Engineering (VLSI Design and Technology)':'VLSI','Mechanical Engineering':'MECH','Mechatronics Engineering':'MTRX','CSE (Cyber Security)':'CSE (Cyber Security)'};return map[name]||name}
function semesterParity(semester){return (+semester%2===0)?'Even Semester':'Odd Semester'}
function batchLabel(batch){return `Batch ${esc(batch||'—')}`}
function groupPrintRows(rows){
  const byDept=[];
  DEPARTMENTS.forEach(dept=>{const list=rows.filter(s=>s.department===dept);if(list.length)byDept.push({department:dept,students:list})});
  rows.filter(s=>!DEPARTMENTS.includes(s.department)).forEach(s=>{let g=byDept.find(x=>x.department===s.department);if(!g){g={department:s.department,students:[]};byDept.push(g)}g.students.push(s)});
  return byDept;
}
function orderedPrintItems(rows){
  const items=[];
  groupPrintRows(rows).forEach(deptGroup=>{
    const dept={type:'department',department:deptGroup.department,groups:[]};
    const batches=[...new Set(deptGroup.students.map(s=>String(s.batch||'—')))].sort((a,b)=>a.localeCompare(b));
    batches.forEach(batch=>{
      ['Odd Semester','Even Semester'].forEach(parity=>{
        const semStudents=deptGroup.students
          .filter(s=>String(s.batch||'—')===batch && semesterParity(s.semester)===parity)
          .sort((a,b)=>{
            const sa=String(a.section||'—'), sb=String(b.section||'—');
            return sa.localeCompare(sb) || String(a.name).localeCompare(String(b.name));
          });
        const sections=[...new Set(semStudents.map(s=>String(s.section||'—')))];
        sections.forEach(section=>{
          const list=semStudents.filter(s=>String(s.section||'—')===section);
          if(list.length) dept.groups.push({batch,parity,section,students:list});
        });
      });
    });
    items.push(dept);
  });
  return items;
}
function printSubgroupHeading(item){return `<div class="print-subgroup-heading"><b>${batchLabel(item.batch)}</b><span>• ${esc(item.parity)}</span><span>• Section ${esc(item.section)}</span></div>`}
function generatePrint(){
  const rows=printScopeData();
  if(!rows.length){alert('No student data matches the selected report.');return}
  const scope=$('printScope').value;
  const title=scope==='student'?'Student Performance Report':scope==='department'?`Department Performance Report — ${$('printDepartment').value}${$('printBatch').value==='ALL'?'':' — Batch '+$('printBatch').value}${$('printSemester').value==='ALL'?'':' — Semester '+$('printSemester').value}${$('printSection').value==='ALL'?'':' — Section '+$('printSection').value}`:'All Students Performance Report';
  const departments=orderedPrintItems(rows);
  const deptBlocks=departments.map((dept,index)=>{
    let html=`<section class="print-department-block ${index?'print-next-department':''}">`;
    html+=`<div class="print-dept-heading"><span>${esc(departmentHeading(dept.department))}</span><b>${esc(dept.department)}</b></div>`;
    dept.groups.forEach(group=>{
      html+=`<div class="print-subgroup">${printSubgroupHeading(group)}<div class="print-student-grid">`;
      group.students.forEach(student=>{html+=printStudentCard(student,0)});
      html+=`</div></div>`;
    });
    html+='</section>';
    return html;
  }).join('');
  const reportHtml=`<div class="print-header"><div><h1>Student Academic Performance Analyzer</h1><h2>${esc(title)}</h2><p>Generated ${new Date().toLocaleString()} • Internal ${settings.internal} • Assignment ${settings.assignment} • Unit Test ${settings.unitTest} • Final Exam ${settings.exam}</p></div></div><div class="print-summary"><div><span>Students</span><b>${rows.length}</b></div><div><span>Average Overall</span><b>${(rows.reduce((a,s)=>a+score(s),0)/rows.length).toFixed(1)}%</b></div><div><span>Average Attendance</span><b>${(rows.reduce((a,s)=>a+s.attendance,0)/rows.length).toFixed(1)}%</b></div><div><span>Good Performance</span><b>${rows.filter(s=>performanceStatus(score(s))==='Good Performance').length}</b></div></div>${deptBlocks}<p class="print-footer">Student Academic Performance Analyzer</p>`;
  $('printReport').innerHTML=reportHtml;
  $('pdfPreviewContent').innerHTML=reportHtml;
  $('printModal').classList.add('hidden');
  $('pdfPreviewModal').classList.remove('hidden');
  $('pdfPreviewModal').setAttribute('aria-hidden','false');
}
function closePdfPreview(){ $('pdfPreviewModal').classList.add('hidden'); $('pdfPreviewModal').setAttribute('aria-hidden','true'); }
async function savePreviewPdf(){
  closePdfPreview();
  if(typeof window.desktopPrint==='function') await window.desktopPrint();
  else { window.print(); }
}

$('studentForm').addEventListener('submit',e=>{e.preventDefault();let s=formStudent(),data=load();const sameGeneral=(x)=>String(x.id).trim().toLowerCase()===String(s.id).trim().toLowerCase()&&String(x.name).trim().toLowerCase()===String(s.name).trim().toLowerCase()&&String(x.department).trim().toLowerCase()===String(s.department).trim().toLowerCase()&&String(x.section||'').trim().toLowerCase()===String(s.section||'').trim().toLowerCase()&&String(x.batch||'').trim()===String(s.batch||'').trim()&&String(x.semester||'').trim()===String(s.semester||'').trim();const matches=data.map((x,idx)=>({x,idx})).filter(v=>sameGeneral(v.x));if(matches.length){if(!confirm(`Student ID ${s.id} already exists for ${s.name}, ${s.department}, Section ${s.section||'—'}, Batch ${s.batch||'—'}, Semester ${s.semester}. Do you want to replace the existing record with these details?`))return;const first=matches[0].idx;data=data.filter(x=>!sameGeneral(x));data.splice(Math.min(first,data.length),0,s)}else data.push(s);save(data);fill(s)});
$('addSubject').onclick=()=>addSubject();
$('addSubjectBottom').onclick=()=>{addSubject();const rows=document.querySelectorAll('.subject-card');rows[rows.length-1]?.scrollIntoView({behavior:'smooth',block:'center'});rows[rows.length-1]?.querySelector('.sub-name')?.focus()};
$('clearForm').onclick=()=>{$('studentForm').reset();$('subjects').innerHTML='';addSubject();$('analysis').classList.add('hidden');$('emptyState').classList.remove('hidden');$('performancePill').textContent='No data';$('performancePill').className='pill neutral'};
$('loadDemo').onclick=()=>{save(DEMO);fill(DEMO[0]);updateSectionFilter()};
$('deptFilter').onchange=()=>{updateSectionFilter();renderTable()};$('sectionFilter').onchange=()=>{updateAnalyticsSemesterFilter();renderTable()};$('batchFilter').onchange=()=>{updateAnalyticsSemesterFilter();renderTable()};$('semesterFilter').onchange=renderTable;$('studentSearch').addEventListener('input',renderTable);
$('clearAll').onclick=()=>{if(confirm('Delete all stored student data from this browser?')){localStorage.removeItem(STORAGE_KEY);renderTable();$('clearForm').click()}};
$('exportData').onclick=()=>{let blob=new Blob([JSON.stringify({settings,theme:getTheme(),data:load()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='student-academic-data.json';a.click();URL.revokeObjectURL(a.href)};
$('menuButton').onclick=()=>{$('settingsPanel').classList.contains('open')?closeSettings():openSettings()};
$('closeSettings').onclick=closeSettings;$('settingsBackdrop').onclick=closeSettings;
$('saveSettings').onclick=()=>{const vals={internal:+$('settingInternal').value,assignment:+$('settingAssignment').value,unitTest:+$('settingUnitTest').value,exam:+$('settingExam').value};if(Object.values(vals).some(v=>!Number.isFinite(v)||v<=0)){alert('All maximum marks must be greater than 0.');return}settings=vals;saveSettings();setTheme($('themeSetting').value);closeSettings()};
$('resetSettings').onclick=()=>{settings={...DEFAULT_SETTINGS};updateSettingsUI();refreshSubjectRows()};
$('addBatch').onclick=()=>{const v=$('newBatch').value.trim();if(!/^\d{4}-\d{2,4}$/.test(v)){alert('Enter a batch like 2025-29.');return}const batches=getBatches();if(batches.includes(v)){alert('This batch already exists.');return}saveBatches([...batches,v]);$('newBatch').value='';};$('batchList').addEventListener('click',e=>{const b=e.target.dataset.batch;if(!b)return;const batches=getBatches();if(b==='2025-29')return;if(confirm(`Remove Batch ${b} from settings? Existing students are not deleted.`))saveBatches(batches.filter(x=>x!==b));});
$('addDepartment').onclick=()=>{const v=$('newDepartment').value.trim();if(!v){alert('Enter a department name.');return}if(DEPARTMENTS.some(d=>d.toLowerCase()===v.toLowerCase())){alert('This department already exists.');return}saveDepartments([...DEPARTMENTS,v]);$('newDepartment').value='';};$('departmentList').addEventListener('click',e=>{const d=e.target.dataset.dept;if(!d)return;if(DEFAULT_DEPARTMENTS.includes(d)){alert('Default departments cannot be removed.');return}if(confirm(`Remove ${d} from settings? Existing student records are not deleted.`))saveDepartments(DEPARTMENTS.filter(x=>x!==d));});
$('themeSetting').onchange=()=>setTheme($('themeSetting').value);
$('printPdf').onclick=openPrintModal;$('closePrintModal').onclick=closePrintModal;$('cancelPrint').onclick=closePrintModal;$('generatePrint').onclick=generatePrint;$('closePdfPreview').onclick=closePdfPreview;$('savePreviewPdf').onclick=savePreviewPdf;
$('printScope').onchange=()=>{const v=$('printScope').value;$('printDepartmentFields').classList.toggle('hidden',v!=='department');$('printStudentField').classList.toggle('hidden',v!=='student');if(v==='department'){populateDeptFilters();updatePrintFilters()}if(v==='student'){populatePrintStudentSemesters();populatePrintStudentOptions()}};
$('printDepartment').onchange=updatePrintFilters;$('printSection').onchange=updatePrintFilters;$('printBatch').onchange=updatePrintFilters;$('printStudentSearch').addEventListener('input',populatePrintStudentOptions);$('printStudentSemester').addEventListener('change',populatePrintStudentOptions);
window.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSettings();closePrintModal()}});
setTheme(getTheme());initDepartments();updateBatchUI();updateSettingsUI();addSubject();updateSectionFilter();renderTable();
